--- Create Product table

CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (id)
);

-- Removed incorrect foreign key constraint
