name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Generate test report
      run: ./gradlew jacocoTestReport
    
    - name: Check code style
      run: ./gradlew spotlessCheck
    
  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/waxes27/store:latest
          ghcr.io/waxes27/store:${{ github.sha }}
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
        cache-from: type=registry,ref=ghcr.io/waxes27/store:buildcache
        cache-to: type=registry,ref=ghcr.io/waxes27/store:buildcache,mode=max
    
    - name: Image digest output
      run: echo "Image pushed to GHCR with tags -- ghcr.io/${{ github.repository_owner }}/store:latest and ghcr.io/${{ github.repository_owner }}/store:${{ github.sha }}"
